### ISSUE TITLE
MTB模块相关问题

### ISSUE THREAD

**Issue by xlx777** [jiaqi-pro/Depression-detection-Graph#3]
作者您好：
我想问一下您模型中的MTB模块是如何使用三个独立的ResNet来分别提取特征图的，这部分代码能不能分享一下？
谢谢

**Comment by jiaqi-pro** [comment]
您好,xlx77:

您所说的带有ResNet结构的MTB，也就是论文中提到的结构，是针对于AVEC 2013， AVEC 2014这类视频数据所设计的。

当前的仓库是针对于AVEC 2019所释放的，采用Conv1d 进行特征提取，本质思想和代码逻辑是近似的。

针对于AVEC 20113，AVEC 2014所涉及的模型-当前论文所提到的，经过整理和测试后，将会在之后进行公开。

到时候会@你，来一起交流进步。

**Comment by xlx777** [comment]
感谢您的回复，期待您公开您的模型。
还有一个问题想向您咨询一下：目前AVEC2013和AVEC2014的官方申请网站已经无法访问，我曾尝试给Michel Valstar教授发邮件询问数据集的申请方法，但没有得到回复。我注意到您这篇文章的作者中有Michel Valstar教授，请问您是否知道目前如何申请AVEC2013和AVEC2014这两个数据集？
谢谢，祝万事胜意。

**Comment by jiaqi-pro** [comment]
您好，xlx77:

我理解您正在寻找AVEC2013和AVEC2014的数据集。然而，对于数据集的申请，我个人并不能提供帮助，因为这不属于我负责的范围。

当前仓库使用的是AVEC 2019数据集，主要是因为它是目前最新并且可获取的数据集。关于AVEC2013和AVEC2014，我建议您再次尝试联系Michel Valstar教授，或者其他可能有这些数据集的研究者或组织。当然，任何数据共享必须符合原始数据分发协议。

我知道我不能提供更多的帮助，但我希望这些建议对您有所帮助。

Best wishes~

**Comment by xlx777** [comment]
谢谢您的建议，我会再联系Michel Valstar教授试一下。
祝万事胜意

**Comment by xlx777** [comment]
作者，您好：
目前我在实验过程中遇到了过拟合的问题，我尝试使用Dropout和正则化等操作发现并没有什么效果，想请教一下您在实验过程中是否有遇到过拟合的问题，您又是怎么解决的？
谢谢，祝好！

**Comment by jiaqi-pro** [comment]
尊敬的xlx777，

您好！过拟合（Overfitting）是机器学习中的一个常见问题，这通常表现为模型在训练数据上的表现优异，但在新的、未曾接触过的数据上的表现却相对较差。

这种情况暗示当前您选择或设计的模型，并未与您现有的数据构建出良好的映射关系。此问题的出现可能是由于数据量不足或模型结构过于复杂，不过这是一个相对的概念。

正如您所述，您采用了Dropout和正则化，这本质上是在尝试对模型结构进行一些微调和控制。

然而，如果您的模型设计本身就比较复杂，且您的数据量相对较少，那么在梯度反向传播过程中，模型可能会“记住”训练数据中的每一个细节，包括噪声。在这种情况下，模型在训练数据上的表现会非常好，但由于它过度拟合了训练数据中的噪声和异常点，所以在新的数据上的表现会相对较差。

针对这个“数据量不足，同时模型结构复杂”的问题，我采用的策略是逐步递进。由于我的数据量是固定的，我并不打算对其进行改动。

我建议您可以从基础的模型开始构建，为实现您所设想的效果和想法，不断尝试和调整。

如果基础模型成功，则可以根据其结果进行不断改进。为了实现这一目标，您需要阅读更多与您所使用数据集相关的研究文章。

如果您是自己制作和采集的数据集，那么使用基础的模型就可能足以满足您的需求。

希望以上建议对您有所帮助！

祝好！

**Comment by xlx777** [comment]
作者您好：
感谢您百忙之中的回复，这对我启发很大，期待之后能和您继续交流。
祝您身体安康，工作顺利！
